// DDC-CWICR-OE: DataDrivenConstruction · OpenConstructionERP
// Copyright (c) 2026 Artem Boiko / DataDrivenConstruction
//
// How-it-works catalog — Communication + Documents domains.
// See ../types.ts for the shape + key convention, and
// ../catalog/overview-estimating.ts for a fully-worked example.

import type { ModuleExplanation } from '../types';

export const communicationDocumentsModules: ModuleExplanation[] = [
  /* ── Communication ────────────────────────────────────────────────────── */
  {
    id: 'contacts',
    route: '/contacts',
    icon: 'Users',
    category: 'communication',
    keywords: 'address book directory companies clients subcontractors suppliers consultants prequalification crm',
    titleKey: 'howto.contacts.title',
    titleDefault: 'Contacts',
    summaryKey: 'howto.contacts.summary',
    summaryDefault: 'One shared address book for every company and person on your projects.',
    whatKey: 'howto.contacts.what',
    whatDefault:
      'Contacts is the directory of every organisation and person you work with - clients, subcontractors, suppliers and consultants - kept once so the same record is reused everywhere. Each entry carries contact details, a country and a prequalification status that flags who is approved to bid or be awarded work.',
    how: [
      { key: 'howto.contacts.how.1', default: 'Click Add Contact, pick a type (client, subcontractor, supplier, consultant and more) and fill in the company, people and contact details.' },
      { key: 'howto.contacts.how.2', default: 'Set a prequalification status - approved, pending, rejected or expired - so you can see at a glance who is cleared to work.' },
      { key: 'howto.contacts.how.3', default: 'Filter by type, country or CRM tag, or search by name and email to find a party fast.' },
      { key: 'howto.contacts.how.4', default: 'Import a list from Excel or CSV with the supplied template, or export the directory back out to Excel.' },
      { key: 'howto.contacts.how.5', default: 'Reuse the same record across the app as an RFI or submittal ball-in-court, a transmittal recipient, a correspondence party or a tender invitee.' },
    ],
    tips: [
      { key: 'howto.contacts.tip.1', default: 'Keep each company in once. A clean directory means RFIs, transmittals and tenders all point at the same party instead of duplicates.' },
      { key: 'howto.contacts.tip.2', default: 'With the Property Development module on, you can convert a contact straight into a lead so the link back to the original record is kept.' },
    ],
    whenKey: 'howto.contacts.when',
    whenDefault: 'Set up the parties here early - most communication and document modules pick people and companies from this directory.',
  },
  {
    id: 'meetings',
    route: '/meetings',
    icon: 'MessageSquare',
    category: 'communication',
    keywords: 'minutes action items agenda attendance recurring series toolbox talk',
    titleKey: 'howto.meetings.title',
    titleDefault: 'Meetings',
    summaryKey: 'howto.meetings.summary',
    summaryDefault: 'Schedule meetings, capture minutes and turn talk into tracked actions.',
    whatKey: 'howto.meetings.what',
    whatDefault:
      'Meetings is where you plan project meetings, record minutes and convert the discussion into action items with an owner and a due date. Decisions and follow-ups stay attached to the project record instead of getting lost in inboxes.',
    how: [
      { key: 'howto.meetings.how.1', default: 'Click New Meeting, choose a type (progress, design, safety, subcontractor, kickoff or closeout), set the date and location, and pick attendees from your contacts.' },
      { key: 'howto.meetings.how.2', default: 'Write the minutes during or after the meeting and attach any supporting files.' },
      { key: 'howto.meetings.how.3', default: 'Record attendance and capture action items, each with a responsible person and a due date so they can be chased.' },
      { key: 'howto.meetings.how.4', default: 'Set up a recurring series for standing site or coordination meetings instead of recreating them each week.' },
      { key: 'howto.meetings.how.5', default: 'Mark a meeting complete to lock its minutes as the agreed record.' },
    ],
    tips: [
      { key: 'howto.meetings.tip.1', default: 'You can import a summary from an existing write-up or transcript and review the extracted attendees and action items before saving.' },
    ],
    whenKey: 'howto.meetings.when',
    whenDefault: 'Use it for any meeting where decisions are made or actions assigned, so the outcome is on the record.',
  },
  {
    id: 'rfi',
    route: '/rfi',
    icon: 'MessageCircle',
    category: 'communication',
    keywords: 'request for information question answer ball in court overdue variation discipline',
    titleKey: 'howto.rfi.title',
    titleDefault: 'RFIs',
    summaryKey: 'howto.rfi.summary',
    summaryDefault: 'Raise a question, set who owns the answer and get it on the record.',
    whatKey: 'howto.rfi.what',
    whatDefault:
      'An RFI (Request for Information) is a formal question to the design team or another party. You raise it, set who owns the next move and a response due date, then track it from Open to Answered to Closed with a ball-in-court badge and an overdue counter so nothing stalls.',
    how: [
      { key: 'howto.rfi.how.1', default: 'Click New RFI and write the subject and question; set a priority and, if useful, a discipline.' },
      { key: 'howto.rfi.how.2', default: 'Set the ball-in-court and assignee and a response due date, and flag any cost or schedule impact.' },
      { key: 'howto.rfi.how.3', default: 'Attach the drawings in question from Documents, or drop a file straight onto the RFI.' },
      { key: 'howto.rfi.how.4', default: 'Track the status with the ball-in-court badge - With you, With them, Answered or Closed - and the days-open and overdue counters.' },
      { key: 'howto.rfi.how.5', default: 'Record the official response, then close the RFI; export the full log for the contract file.' },
    ],
    tips: [
      { key: 'howto.rfi.tip.1', default: 'When an answer carries cost, you can spin the RFI straight into a Variation so the change is not lost.' },
      { key: 'howto.rfi.tip.2', default: 'Use the awaiting-my-response filter to see only the RFIs that are in your court right now.' },
    ],
    whenKey: 'howto.rfi.when',
    whenDefault: 'Use it whenever you need a documented answer to a question that could affect cost, time or buildability.',
  },
  {
    id: 'correspondence',
    route: '/correspondence',
    icon: 'Mail',
    category: 'communication',
    keywords: 'letters notices emails memos register log claims evidence trail incoming outgoing',
    titleKey: 'howto.correspondence.title',
    titleDefault: 'Correspondence',
    summaryKey: 'howto.correspondence.summary',
    summaryDefault: 'A dated register of every formal letter, notice, email and memo.',
    whatKey: 'howto.correspondence.what',
    whatDefault:
      'Correspondence is a contemporaneous register of the formal letters, notices, emails and memos exchanged with project parties. It gives you a single, dated thread of communication that stands up as evidence if a dispute or claim arises.',
    how: [
      { key: 'howto.correspondence.how.1', default: 'Click to log an entry, set the direction (incoming or outgoing) and the type - letter, email, notice or memo.' },
      { key: 'howto.correspondence.how.2', default: 'Record the parties (from and to), pick them from your contacts where possible, and capture the subject and date.' },
      { key: 'howto.correspondence.how.3', default: 'Attach the source file - the scanned letter or saved email - so the original is kept with the entry.' },
      { key: 'howto.correspondence.how.4', default: 'Link the entry to the related transmittal, RFI, document or contact so the whole thread stays traceable.' },
      { key: 'howto.correspondence.how.5', default: 'Filter and search the register to reconstruct a sequence of events when you need it.' },
    ],
    tips: [
      { key: 'howto.correspondence.tip.1', default: 'Log items as they happen. A complete, dated register is far stronger evidence than one rebuilt months later.' },
      { key: 'howto.correspondence.tip.2', default: 'Inbound email auto-import is not wired up yet, so entries are added by hand today.' },
    ],
    whenKey: 'howto.correspondence.when',
    whenDefault: 'Use it for any formal communication that might matter to the contract - notices, claims and key decisions especially.',
  },
  {
    id: 'collaboration',
    route: '/collaboration',
    icon: 'Users',
    category: 'communication',
    keywords: 'real-time presence comments discussion viewpoints co-editing yjs webrtc multiplayer',
    titleKey: 'howto.collaboration.title',
    titleDefault: 'Collaboration',
    summaryKey: 'howto.collaboration.summary',
    summaryDefault: 'A per-project hub for discussion, viewpoints and who is online now.',
    whatKey: 'howto.collaboration.what',
    whatDefault:
      'Collaboration is the per-project hub for working together: a threaded discussion, saved viewpoints and a live roster of who is connected right now and what they have open for editing. The same comment thread also appears in context on BOQ positions, documents, RFIs and BIM elements.',
    how: [
      { key: 'howto.collaboration.how.1', default: 'Open the hub on a project to see the project-wide discussion, the active-now roster and saved viewpoints in one place.' },
      { key: 'howto.collaboration.how.2', default: 'Post and reply in the discussion thread, or comment directly on a BOQ position, document, RFI or BIM element where the same thread appears.' },
      { key: 'howto.collaboration.how.3', default: 'Save a viewpoint to mark a discussion topic, or capture a camera-anchored viewpoint from the BIM viewer or PDF takeoff.' },
      { key: 'howto.collaboration.how.4', default: 'Watch the active-now roster to see who else is in the project and which records you have locked for editing.' },
      { key: 'howto.collaboration.how.5', default: 'Set your display name so teammates see who you are as a cursor and presence label while editing a BOQ together.' },
    ],
    tips: [
      { key: 'howto.collaboration.tip.1', default: 'Live co-editing of a BOQ syncs peer-to-peer between browsers and merges concurrent edits with no data loss.' },
      { key: 'howto.collaboration.tip.2', default: 'For persistent server-side sync across sessions, a WebSocket provider has to be configured in your deployment.' },
    ],
    whenKey: 'howto.collaboration.when',
    whenDefault: 'Reach for it when more than one person is working a project and you need to discuss, point at the same thing and see who is online.',
  },

  /* ── Documents ────────────────────────────────────────────────────────── */
  {
    id: 'submittals',
    route: '/submittals',
    icon: 'FileText',
    category: 'documents',
    keywords: 'shop drawings product data samples certificates review approval revise resubmit days in court',
    titleKey: 'howto.submittals.title',
    titleDefault: 'Submittals',
    summaryKey: 'howto.submittals.summary',
    summaryDefault: 'Move shop drawings, product data and samples through review and approval.',
    whatKey: 'howto.submittals.what',
    whatDefault:
      'Submittals is where supplier and subcontractor documents - shop drawings, product data sheets, samples and certificates - are logged and taken through review so nothing goes to site without sign-off. Each one moves through a clear status pipeline with due-date tracking.',
    how: [
      { key: 'howto.submittals.how.1', default: 'Create a submittal, pick its type (shop drawing, product data, sample, certificate and more) and reference the supporting documents.' },
      { key: 'howto.submittals.how.2', default: 'Submit it to start the review; it moves from Draft to Submitted to Under Review.' },
      { key: 'howto.submittals.how.3', default: 'The reviewer records a decision - Approved, Approved as Noted, Revise and Resubmit, or Rejected.' },
      { key: 'howto.submittals.how.4', default: 'If changes are requested, edit and resubmit to start a new revision; watch the due-date and days-in-court badges so reviews do not stall.' },
      { key: 'howto.submittals.how.5', default: 'Link a submittal to the BOQ positions it covers so you can see which items have approved documentation before they are built.' },
    ],
    tips: [
      { key: 'howto.submittals.tip.1', default: 'Upload the files in the Documents module first, then reference them on the submittal - the same source file can back several records.' },
      { key: 'howto.submittals.tip.2', default: 'A submittal can be pushed through an approval route when a formal, routed sign-off is required.' },
    ],
    whenKey: 'howto.submittals.when',
    whenDefault: 'Use it for anything that needs review before it is installed or ordered, so approvals are tracked, not assumed.',
  },
  {
    id: 'transmittals',
    route: '/transmittals',
    icon: 'Send',
    category: 'documents',
    keywords: 'distribution record issue receipt acknowledgement purpose for approval for construction evidence',
    titleKey: 'howto.transmittals.title',
    titleDefault: 'Transmittals',
    summaryKey: 'howto.transmittals.summary',
    summaryDefault: 'A formal record of which documents you issued, to whom and when.',
    whatKey: 'howto.transmittals.what',
    whatDefault:
      'A transmittal is the formal distribution record created when you issue drawings or specifications to another party: what was sent, to whom, the purpose, and whether they acknowledged receipt. It is the dated evidence trail behind your submittals and correspondence.',
    how: [
      { key: 'howto.transmittals.how.1', default: 'Create a transmittal, set the subject and recipient, and choose the purpose code - For Approval, For Information, For Construction, For Review, For Tender or For Record.' },
      { key: 'howto.transmittals.how.2', default: 'Add the document revisions being sent by picking the right versions from the common data environment.' },
      { key: 'howto.transmittals.how.3', default: 'Issue the transmittal to lock the record of what was distributed; until then it stays a draft.' },
      { key: 'howto.transmittals.how.4', default: 'Track the status - Draft, Issued, Responded - so you know who has acknowledged or replied.' },
    ],
    tips: [
      { key: 'howto.transmittals.tip.1', default: 'A purpose code like For Approval signals a response is expected, while For Information does not - pick it deliberately.' },
      { key: 'howto.transmittals.tip.2', default: 'Issuing controlled revisions keeps the transmittal tied to the exact versions in the common data environment.' },
    ],
    whenKey: 'howto.transmittals.when',
    whenDefault: 'Use it whenever you formally hand documents to a subcontractor or consultant and need proof of issue.',
  },
  {
    id: 'cde',
    route: '/cde',
    icon: 'FolderOpen',
    category: 'documents',
    keywords: 'common data environment iso 19650 containers wip shared published archived revisions suitability gate',
    titleKey: 'howto.cde.title',
    titleDefault: 'Common Data Environment',
    summaryKey: 'howto.cde.summary',
    summaryDefault: 'One agreed source of truth that moves documents through controlled states.',
    whatKey: 'howto.cde.what',
    whatDefault:
      'The Common Data Environment (CDE) organises project documents into ISO 19650 containers and moves each revision through Work in Progress, Shared, Published and Archived, so everyone always works off the right version. Promotions are gated by role and a full history is kept per container.',
    how: [
      { key: 'howto.cde.how.1', default: 'Create a container for a document, set its discipline, then add revisions as the work develops.' },
      { key: 'howto.cde.how.2', default: 'Promote a revision through the states - Work in Progress, Shared, Published, then Archived - as it becomes fit to share, use and finally retire.' },
      { key: 'howto.cde.how.3', default: 'Each state change crosses a gate that needs the right role, so editors and viewers cannot promote past their permissions.' },
      { key: 'howto.cde.how.4', default: 'Open the history drawer to see every transition and revision for a container.' },
      { key: 'howto.cde.how.5', default: 'Issue the controlled revisions onward as transmittals when documents need to go to another party.' },
    ],
    tips: [
      { key: 'howto.cde.tip.1', default: 'Upload files in the File Manager first, then organise and control them here - the CDE governs states and versions, not raw storage.' },
      { key: 'howto.cde.tip.2', default: 'Publishing a revision is the signal that it is approved for use; keep work-in-progress drafts in the WIP state until then.' },
    ],
    whenKey: 'howto.cde.when',
    whenDefault: 'Use it on any project that needs disciplined version control and a clear shared-versus-published status for documents.',
  },
  {
    id: 'photos',
    route: '/photos',
    icon: 'Scan',
    category: 'documents',
    keywords: 'site photos gallery timeline exif gps progress defects deliveries safety lightbox',
    titleKey: 'howto.photos.title',
    titleDefault: 'Project Photos',
    summaryKey: 'howto.photos.summary',
    summaryDefault: 'A dated, geotagged gallery of what the site looked like.',
    whatKey: 'howto.photos.what',
    whatDefault:
      'Project Photos is the gallery for site documentation. As photos upload it reads their EXIF capture date and GPS, so progress, defect, delivery and safety shots sort chronologically and on a timeline - giving you proof of what the site looked like, and when.',
    how: [
      { key: 'howto.photos.how.1', default: 'Upload photos by dragging them in; the gallery reads each one for capture date and GPS location automatically.' },
      { key: 'howto.photos.how.2', default: 'Categorise as site, progress, defect, delivery, safety or other, and accept the suggested category when a likely defect is spotted.' },
      { key: 'howto.photos.how.3', default: 'Tag and caption in batches to keep large sets organised.' },
      { key: 'howto.photos.how.4', default: 'Switch between the grid and the timeline, and filter by category or search to find a shot.' },
      { key: 'howto.photos.how.5', default: 'Open any photo in the lightbox to view it full size with its date, location and tags.' },
    ],
    tips: [
      { key: 'howto.photos.tip.1', default: 'Photos taken on a phone usually carry date and GPS in their EXIF data, so they place themselves on the timeline and map without extra typing.' },
      { key: 'howto.photos.tip.2', default: 'The photos sit alongside the rest of the project files in the File Manager.' },
    ],
    whenKey: 'howto.photos.when',
    whenDefault: 'Use it to record progress over time and to capture defects, deliveries and safety conditions as dated evidence.',
  },
  {
    id: 'markups',
    route: '/markups',
    icon: 'PencilRuler',
    category: 'documents',
    keywords: 'annotations clouds arrows text stamps measurements distance area count revisions compare pdf',
    titleKey: 'howto.markups.title',
    titleDefault: 'Markups',
    summaryKey: 'howto.markups.summary',
    summaryDefault: 'Drawing comments and measurements that do not get lost.',
    whatKey: 'howto.markups.what',
    whatDefault:
      'Markups are the review annotations placed on project drawings - clouds, arrows, text, stamps and distance, area or count measurements. Each one can be assigned to a person and tracked to resolution, so review comments on a PDF stay visible and accountable instead of scattered.',
    how: [
      { key: 'howto.markups.how.1', default: 'Open a project PDF in the inline annotator and add clouds, arrows, text, stamps or distance, area and count measurements.' },
      { key: 'howto.markups.how.2', default: 'Assign a markup to a person and give it a note so the owner knows what to fix.' },
      { key: 'howto.markups.how.3', default: 'Track each markup through active, resolved and archived, and filter the list by type or status.' },
      { key: 'howto.markups.how.4', default: 'Open any markup straight on its source drawing to see it in context.' },
      { key: 'howto.markups.how.5', default: 'Export the markups to CSV for a review log, or jump to Compare to check two revisions of a drawing side by side.' },
    ],
    tips: [
      { key: 'howto.markups.tip.1', default: 'A markup can be pushed through an approval route when the comments need formal sign-off.' },
      { key: 'howto.markups.tip.2', default: 'Use the revision compare to spot exactly what changed between two issues before you re-mark a drawing.' },
    ],
    whenKey: 'howto.markups.when',
    whenDefault: 'Use it to review and comment on drawings, redline issues and take quick measurements off a PDF.',
  },
];
