import psycopg2
c = psycopg2.connect(host='127.0.0.1', port=50554, user='postgres', dbname='postgres')
cur = c.cursor()
cur.execute("SELECT count(*) FROM information_schema.tables WHERE table_name LIKE 'oe_%'")
print('oe tables:', cur.fetchone())
cur.execute('SELECT count(*) FROM oe_costs_item')
print('items:', cur.fetchone())
cur.execute('SELECT count(*) FROM oe_costs_catalog')
print('catalogs:', cur.fetchone())
cur.execute("SELECT region, count(*) FROM oe_costs_item GROUP BY region ORDER BY 2 DESC LIMIT 10")
print('regions:', cur.fetchall())
cur.execute("SELECT count(*) FROM oe_costs_item WHERE code LIKE 'WB-%' OR source IN ('won_or_filed_tender','operator_pricelist','supplier_web_anchor')")
print('existing tenderops-ish rows:', cur.fetchone())
cur.execute("SELECT id, source, region, is_active, code, left(description,60), rate, currency FROM oe_costs_item WHERE source NOT IN ('cwicr') OR region IS NULL LIMIT 5")
for r in cur.fetchall(): print(r)
