# DDC-CWICR-OE: DataDrivenConstruction · OpenConstructionERP
# Copyright (c) 2026 Artem Boiko / DataDrivenConstruction
from __future__ import annotations

from app.core.demo_projects import DemoTemplate

# ---------------------------------------------------------------------------
# Partner pack: south-africa - Bulk Water & Roads Infrastructure, Cape Town
# ---------------------------------------------------------------------------
# Second South African demo for the pack, deliberately a heavy-civil
# engineering project rather than a building, so the pack lands two distinct
# in-market archetypes (a Sandton mixed-use building plus this Cape Town
# infrastructure scheme). Programme: a municipal bulk-water and roads upgrade
# in the City of Cape Town (Western Cape) comprising a new reinforced-concrete
# reservoir, a pump station, large-diameter bulk pipelines, a road upgrade
# with stormwater, and a small wastewater treatment-works extension.
#
# Measurement: SANS 1200 Standardized Specification for Civil Engineering
# Construction - the South African civil-engineering measurement and
# specification standard. The platform classification is carried as CSI
# MasterFormat 2018 (the standard the demo harness understands) and the
# SANS 1200 sub-section reference is kept in each classification dict under
# the "sans1200" key (for example SANS 1200 DA earthworks, G concrete, L
# pipe trenches, LB bedding, LD sewers, MJ segmented paving). Rates are
# Cape Town 2026 market rates in South African Rand (ZAR), exclusive of VAT
# (15% carried as a separate markup line). Procurement follows the General
# Conditions of Contract for Construction Works (GCC 2015, SAICE), the usual
# South African public-works civil engineering contract.
# ---------------------------------------------------------------------------

TEMPLATE = DemoTemplate(
    demo_id="infrastructure-capetown",
    project_name="Cape Flats Bulk Water & Roads Infrastructure Upgrade",
    project_description=(
        "Municipal bulk-water and roads infrastructure upgrade for the City of "
        "Cape Town in the Cape Flats area, Western Cape. The scheme comprises a "
        "new 25 Ml reinforced-concrete reservoir, a raw- and potable-water pump "
        "station, approximately 12 km of large-diameter bulk water and sewer "
        "pipelines, a 6 km arterial road upgrade with kerbing, stormwater and "
        "sidewalks, and a modular extension to an existing wastewater treatment "
        "works. Designed and measured on SANS 1200 (Standardized Specification "
        "for Civil Engineering Construction) with TRH road-pavement design and "
        "SANS 10100 for the concrete structures. Procured under GCC 2015 "
        "(SAICE). Estimated direct construction cost approx. ZAR 410 million, "
        "before VAT and overheads."
    ),
    region="ZA",
    classification_standard="masterformat",
    currency="ZAR",
    locale="en-ZA",
    address={
        "street": "Jakes Gerwel Drive, Bishop Lavis",
        "city": "Cape Town",
        "postcode": "7490",
        "country": "South Africa",
        "lat": -33.9419,
        "lng": 18.5897,
    },
    validation_rule_sets=["masterformat", "boq_quality", "project_completeness"],
    boq_name="Bill of Quantities - SANS 1200 Civil Engineering Construction",
    boq_description=(
        "Detailed bill of quantities measured on SANS 1200 (Standardized "
        "Specification for Civil Engineering Construction), all sections from "
        "Site Clearance and Earthworks to Roads, Pipelines and Structures. "
        "Rates exclusive of VAT; Cape Town 2026 price level (ZAR)."
    ),
    boq_metadata={
        "standard": "SANS 1200 Standardized Specification for Civil Engineering Construction",
        "phase": "Detailed Estimate / Tender BoQ",
        "base_date": "2026-Q1",
        "price_level": "Cape Town 2026 (ZAR, excl. VAT)",
        "cidb_grade": "8CE (Civil Engineering)",
        "contract": "GCC 2015 (SAICE)",
    },
    sections=[
        # ── A - Preliminary & General (SANS 1200 A / GCC 2015) ───────────
        (
            "A",
            "A - Preliminary & General",
            {"masterformat": "01", "sans1200": "SANS 1200 A"},
            [
                (
                    "A.01",
                    "Contractor's site establishment, offices & camp (Establishment)",
                    "lsum",
                    1,
                    4250000.00,
                    {"masterformat": "01 50 00", "sans1200": "A"},
                ),
                (
                    "A.02",
                    "Provision of construction plant & equipment (Plant)",
                    "month",
                    24,
                    685000.00,
                    {"masterformat": "01 54 00", "sans1200": "A"},
                ),
                (
                    "A.03",
                    "Site management, engineering & supervision staff (Site staff)",
                    "month",
                    24,
                    485000.00,
                    {"masterformat": "01 31 00", "sans1200": "A"},
                ),
                (
                    "A.04",
                    "Occupational health & safety, OHS Act compliance (Health & safety)",
                    "lsum",
                    1,
                    1650000.00,
                    {"masterformat": "01 35 29", "sans1200": "A"},
                ),
                (
                    "A.05",
                    "Accommodation of traffic & temporary deviations (Traffic accommodation)",
                    "lsum",
                    1,
                    2850000.00,
                    {"masterformat": "01 55 26", "sans1200": "A"},
                ),
                (
                    "A.06",
                    "Contractor's all-risk insurance, bonds & guarantees (Insurance)",
                    "lsum",
                    1,
                    3850000.00,
                    {"masterformat": "01 21 00", "sans1200": "A"},
                ),
                (
                    "A.07",
                    "Survey, setting-out & as-built records (Survey)",
                    "lsum",
                    1,
                    985000.00,
                    {"masterformat": "01 71 23", "sans1200": "A"},
                ),
                (
                    "A.08",
                    "Environmental management plan & rehabilitation (EMP)",
                    "lsum",
                    1,
                    1450000.00,
                    {"masterformat": "01 57 00", "sans1200": "A"},
                ),
                (
                    "A.09",
                    "Quality control, materials testing & laboratory (QC testing)",
                    "lsum",
                    1,
                    1250000.00,
                    {"masterformat": "01 45 00", "sans1200": "A"},
                ),
            ],
        ),
        # ── B - Site Clearance & Earthworks (SANS 1200 C / DA / DB) ──────
        (
            "B",
            "B - Site Clearance & Earthworks",
            {"masterformat": "31", "sans1200": "SANS 1200 DA"},
            [
                (
                    "B.01",
                    "Clear & grub site, remove vegetation & obstructions (Clear & grub)",
                    "ha",
                    28,
                    38500.00,
                    {"masterformat": "31 11 00", "sans1200": "C"},
                ),
                (
                    "B.02",
                    "Strip & stockpile topsoil for re-use (Topsoil strip)",
                    "m3",
                    18500,
                    95.00,
                    {"masterformat": "31 14 13", "sans1200": "DA"},
                ),
                (
                    "B.03",
                    "Bulk excavation in all materials except hard rock (Bulk excavation)",
                    "m3",
                    145000,
                    125.00,
                    {"masterformat": "31 23 16", "sans1200": "DA"},
                ),
                (
                    "B.04",
                    "Extra over excavation in hard rock requiring blasting (Hard-rock excavation)",
                    "m3",
                    22000,
                    385.00,
                    {"masterformat": "31 23 16", "sans1200": "DA"},
                ),
                (
                    "B.05",
                    "Fill from cut, placed & compacted to 95% MOD (Fill from cut)",
                    "m3",
                    98000,
                    85.00,
                    {"masterformat": "31 23 23", "sans1200": "DB"},
                ),
                (
                    "B.06",
                    "Imported G5 selected fill, placed & compacted (Imported fill)",
                    "m3",
                    32000,
                    245.00,
                    {"masterformat": "31 23 23", "sans1200": "DB"},
                ),
                (
                    "B.07",
                    "Cart away surplus & unsuitable material to spoil (Cart away)",
                    "m3",
                    64000,
                    165.00,
                    {"masterformat": "31 23 23", "sans1200": "DA"},
                ),
                (
                    "B.08",
                    "Geotextile separation & filter fabric (Geotextile)",
                    "m2",
                    42000,
                    65.00,
                    {"masterformat": "31 32 19", "sans1200": "DB"},
                ),
                (
                    "B.09",
                    "Soil stabilisation, lime/cement treatment of in-situ (Soil stabilisation)",
                    "m3",
                    18500,
                    285.00,
                    {"masterformat": "31 32 13", "sans1200": "DB"},
                ),
            ],
        ),
        # ── C - Reservoir Structure (SANS 1200 G / SANS 10100) ───────────
        (
            "C",
            "C - Reinforced Concrete Reservoir (25 Ml)",
            {"masterformat": "03", "sans1200": "SANS 1200 G"},
            [
                (
                    "C.01",
                    "Excavate for reservoir base & bulk earthworks (Reservoir excavation)",
                    "m3",
                    28000,
                    135.00,
                    {"masterformat": "31 23 16", "sans1200": "DA"},
                ),
                (
                    "C.02",
                    "Blinding concrete 75mm, 15 MPa under base (Blinding)",
                    "m2",
                    6200,
                    165.00,
                    {"masterformat": "03 30 00", "sans1200": "G"},
                ),
                (
                    "C.03",
                    "Reinforced concrete base slab, 35 MPa water-retaining (Base slab)",
                    "m3",
                    3800,
                    3450.00,
                    {"masterformat": "03 31 00", "sans1200": "G"},
                ),
                (
                    "C.04",
                    "Reinforced concrete perimeter & division walls, 35 MPa (Walls)",
                    "m3",
                    4600,
                    3850.00,
                    {"masterformat": "03 30 00", "sans1200": "G"},
                ),
                (
                    "C.05",
                    "Reinforced concrete columns & roof slab, 35 MPa (Roof structure)",
                    "m3",
                    3200,
                    3950.00,
                    {"masterformat": "03 30 00", "sans1200": "G"},
                ),
                (
                    "C.06",
                    "High-yield reinforcement to reservoir, SANS 920 (Reservoir rebar)",
                    "t",
                    1850,
                    24500.00,
                    {"masterformat": "03 21 00", "sans1200": "G"},
                ),
                (
                    "C.07",
                    "Formwork to water-retaining concrete, fair finish (Reservoir formwork)",
                    "m2",
                    14500,
                    425.00,
                    {"masterformat": "03 11 00", "sans1200": "G"},
                ),
                (
                    "C.08",
                    "PVC waterstops to construction & movement joints (Waterstops)",
                    "m",
                    2400,
                    385.00,
                    {"masterformat": "03 15 13", "sans1200": "G"},
                ),
                (
                    "C.09",
                    "Internal waterproof cementitious coating to tank (Tank coating)",
                    "m2",
                    9800,
                    285.00,
                    {"masterformat": "07 16 00", "sans1200": "G"},
                ),
                (
                    "C.10",
                    "Hydrostatic water test & disinfection of reservoir (Water test)",
                    "lsum",
                    1,
                    685000.00,
                    {"masterformat": "33 16 00", "sans1200": "G"},
                ),
                (
                    "C.11",
                    "Reservoir handrailing, access ladders & covers (Reservoir metalwork)",
                    "lsum",
                    1,
                    1250000.00,
                    {"masterformat": "05 52 00", "sans1200": "G"},
                ),
            ],
        ),
        # ── D - Pump Station (SANS 1200 G / mechanical) ──────────────────
        (
            "D",
            "D - Water Pump Station",
            {"masterformat": "33", "sans1200": "SANS 1200 G"},
            [
                (
                    "D.01",
                    "Reinforced concrete pump-station structure, 35 MPa (Pump-station structure)",
                    "m3",
                    1450,
                    4250.00,
                    {"masterformat": "03 30 00", "sans1200": "G"},
                ),
                (
                    "D.02",
                    "Reinforcement & formwork to pump station (Pump-station concrete works)",
                    "t",
                    185,
                    25500.00,
                    {"masterformat": "03 21 00", "sans1200": "G"},
                ),
                (
                    "D.03",
                    "Vertical turbine & end-suction pump sets, duty/standby (Pump sets)",
                    "pcs",
                    6,
                    1850000.00,
                    {"masterformat": "43 21 39", "sans1200": "G"},
                ),
                (
                    "D.04",
                    "Pump-station pipework, valves & manifold, ductile iron (Station pipework)",
                    "lsum",
                    1,
                    4850000.00,
                    {"masterformat": "40 05 00", "sans1200": "LB"},
                ),
                (
                    "D.05",
                    "Surge protection & pressure vessel (Surge protection)",
                    "lsum",
                    1,
                    2850000.00,
                    {"masterformat": "43 21 00", "sans1200": "G"},
                ),
                (
                    "D.06",
                    "Pump-station electrical, MCC, VSDs & SCADA (Pump-station electrical)",
                    "lsum",
                    1,
                    5850000.00,
                    {"masterformat": "26 24 19", "sans1200": "G"},
                ),
                (
                    "D.07",
                    "Standby diesel generator 800 kVA & changeover (Standby generator)",
                    "pcs",
                    1,
                    2450000.00,
                    {"masterformat": "26 32 13", "sans1200": "G"},
                ),
                (
                    "D.08",
                    "Overhead travelling crane & lifting equipment (Lifting equipment)",
                    "pcs",
                    1,
                    1250000.00,
                    {"masterformat": "41 22 13", "sans1200": "G"},
                ),
            ],
        ),
        # ── E - Bulk Water Pipelines (SANS 1200 L / LB) ──────────────────
        (
            "E",
            "E - Bulk Water Pipelines",
            {"masterformat": "33", "sans1200": "SANS 1200 L"},
            [
                (
                    "E.01",
                    "Excavate pipe trench in all materials, to 3m deep (Trench excavation)",
                    "m3",
                    78000,
                    145.00,
                    {"masterformat": "31 23 16", "sans1200": "LB"},
                ),
                (
                    "E.02",
                    "Extra over trench excavation in hard rock (Trench rock)",
                    "m3",
                    9800,
                    425.00,
                    {"masterformat": "31 23 16", "sans1200": "LB"},
                ),
                (
                    "E.03",
                    "Selected granular bedding & blanket to pipes (Pipe bedding)",
                    "m3",
                    22000,
                    285.00,
                    {"masterformat": "31 23 23", "sans1200": "LB"},
                ),
                (
                    "E.04",
                    "Supply & lay 800mm steel bulk water main, lined (800mm steel main)",
                    "m",
                    4200,
                    6850.00,
                    {"masterformat": "33 11 00", "sans1200": "L"},
                ),
                (
                    "E.05",
                    "Supply & lay 500mm ductile-iron water main (500mm DI main)",
                    "m",
                    5600,
                    4250.00,
                    {"masterformat": "33 11 00", "sans1200": "L"},
                ),
                (
                    "E.06",
                    "Supply & lay 315mm uPVC reticulation main, SANS 966 (315mm uPVC main)",
                    "m",
                    8800,
                    1450.00,
                    {"masterformat": "33 11 13", "sans1200": "L"},
                ),
                (
                    "E.07",
                    "Backfill trench & compact to 90% MOD in layers (Trench backfill)",
                    "m3",
                    68000,
                    95.00,
                    {"masterformat": "31 23 23", "sans1200": "LB"},
                ),
                (
                    "E.08",
                    "Reinforced concrete thrust & anchor blocks (Thrust blocks)",
                    "m3",
                    1450,
                    3650.00,
                    {"masterformat": "03 30 00", "sans1200": "LB"},
                ),
                (
                    "E.09",
                    "Valves, hydrants, air valves & scour chambers (Valves & chambers)",
                    "pcs",
                    240,
                    42500.00,
                    {"masterformat": "33 12 16", "sans1200": "LB"},
                ),
                (
                    "E.10",
                    "Pressure testing & disinfection of pipelines (Pipeline testing)",
                    "m",
                    18600,
                    145.00,
                    {"masterformat": "33 11 00", "sans1200": "L"},
                ),
                (
                    "E.11",
                    "Detectable marker tape & pipeline locating wire (Marker tape)",
                    "m",
                    18600,
                    38.00,
                    {"masterformat": "33 05 26", "sans1200": "LB"},
                ),
            ],
        ),
        # ── F - Sewer Pipelines (SANS 1200 LD / DB) ──────────────────────
        (
            "F",
            "F - Sewer & Outfall Pipelines",
            {"masterformat": "33", "sans1200": "SANS 1200 LD"},
            [
                (
                    "F.01",
                    "Excavate sewer trench in all materials, to 4m deep (Sewer trench excavation)",
                    "m3",
                    42000,
                    165.00,
                    {"masterformat": "31 23 16", "sans1200": "LD"},
                ),
                (
                    "F.02",
                    "Granular bedding & support to sewer pipes (Sewer bedding)",
                    "m3",
                    12500,
                    285.00,
                    {"masterformat": "31 23 23", "sans1200": "LD"},
                ),
                (
                    "F.03",
                    "Supply & lay 600mm sewer pipe, HDPE SANS 4427 (600mm HDPE sewer)",
                    "m",
                    3800,
                    3850.00,
                    {"masterformat": "33 31 00", "sans1200": "LD"},
                ),
                (
                    "F.04",
                    "Supply & lay 315mm sewer pipe, uPVC SANS 791 (315mm uPVC sewer)",
                    "m",
                    5200,
                    1250.00,
                    {"masterformat": "33 31 13", "sans1200": "LD"},
                ),
                (
                    "F.05",
                    "Precast concrete manholes, to depth, SANS 1294 (Manholes)",
                    "pcs",
                    185,
                    28500.00,
                    {"masterformat": "33 39 13", "sans1200": "LD"},
                ),
                (
                    "F.06",
                    "Backfill sewer trench & compact in layers (Sewer backfill)",
                    "m3",
                    36000,
                    95.00,
                    {"masterformat": "31 23 23", "sans1200": "LD"},
                ),
                (
                    "F.07",
                    "Reinforced concrete encasement to shallow sewers (Pipe encasement)",
                    "m3",
                    980,
                    3650.00,
                    {"masterformat": "03 30 00", "sans1200": "LD"},
                ),
                (
                    "F.08",
                    "CCTV inspection & air testing of sewers (Sewer testing)",
                    "m",
                    9000,
                    125.00,
                    {"masterformat": "33 01 30", "sans1200": "LD"},
                ),
            ],
        ),
        # ── G - Road Upgrade & Pavement (SANS 1200 ME / TRH) ─────────────
        (
            "G",
            "G - Road Upgrade & Pavement Layers",
            {"masterformat": "32", "sans1200": "SANS 1200 ME"},
            [
                (
                    "G.01",
                    "Prepare & compact roadbed to 93% MOD (Roadbed preparation)",
                    "m2",
                    86000,
                    48.00,
                    {"masterformat": "32 11 23", "sans1200": "ME"},
                ),
                (
                    "G.02",
                    "Selected subgrade layer G7, 150mm compacted (Subgrade layer)",
                    "m3",
                    14500,
                    245.00,
                    {"masterformat": "32 11 23", "sans1200": "ME"},
                ),
                (
                    "G.03",
                    "Subbase, G5 natural gravel, 150mm compacted (Subbase)",
                    "m3",
                    13800,
                    365.00,
                    {"masterformat": "32 11 26", "sans1200": "ME"},
                ),
                (
                    "G.04",
                    "Base course, G2 crushed stone, 150mm compacted (Base course)",
                    "m3",
                    13800,
                    545.00,
                    {"masterformat": "32 11 26", "sans1200": "ME"},
                ),
                (
                    "G.05",
                    "Prime coat to base, MC-30 cutback bitumen (Prime coat)",
                    "m2",
                    72000,
                    38.00,
                    {"masterformat": "32 12 13", "sans1200": "ME"},
                ),
                (
                    "G.06",
                    "Asphalt surfacing, 40mm continuously graded (Asphalt surfacing)",
                    "m2",
                    68000,
                    285.00,
                    {"masterformat": "32 12 16", "sans1200": "ME"},
                ),
                (
                    "G.07",
                    "Double-seal surfacing to side roads (19/6.7mm) (Double seal)",
                    "m2",
                    18000,
                    145.00,
                    {"masterformat": "32 12 36", "sans1200": "ME"},
                ),
                (
                    "G.08",
                    "Precast concrete kerbing & channelling (Kerbs & channels)",
                    "m",
                    12200,
                    385.00,
                    {"masterformat": "32 16 13", "sans1200": "MJ"},
                ),
                (
                    "G.09",
                    "Concrete-block paved sidewalks & islands (Sidewalk paving)",
                    "m2",
                    9800,
                    485.00,
                    {"masterformat": "32 14 13", "sans1200": "MJ"},
                ),
                (
                    "G.10",
                    "Road marking, thermoplastic & studs (Road marking)",
                    "m2",
                    4200,
                    285.00,
                    {"masterformat": "32 17 23", "sans1200": "ME"},
                ),
                (
                    "G.11",
                    "Road signs, guardrails & furniture (Road furniture)",
                    "lsum",
                    1,
                    2850000.00,
                    {"masterformat": "34 41 00", "sans1200": "ME"},
                ),
                (
                    "G.12",
                    "Street lighting, masts, luminaires & cabling (Street lighting)",
                    "pcs",
                    240,
                    32500.00,
                    {"masterformat": "26 56 00", "sans1200": "ME"},
                ),
            ],
        ),
        # ── H - Stormwater Drainage (SANS 1200 LB / DB) ──────────────────
        (
            "H",
            "H - Stormwater Drainage",
            {"masterformat": "33", "sans1200": "SANS 1200 LB"},
            [
                (
                    "H.01",
                    "Excavate for stormwater pipes & structures (Stormwater excavation)",
                    "m3",
                    28000,
                    145.00,
                    {"masterformat": "31 23 16", "sans1200": "LB"},
                ),
                (
                    "H.02",
                    "Supply & lay 900mm concrete stormwater pipe, SANS 677 (900mm pipe)",
                    "m",
                    2400,
                    3850.00,
                    {"masterformat": "33 41 00", "sans1200": "LB"},
                ),
                (
                    "H.03",
                    "Supply & lay 600mm concrete stormwater pipe (600mm pipe)",
                    "m",
                    3800,
                    1850.00,
                    {"masterformat": "33 41 00", "sans1200": "LB"},
                ),
                (
                    "H.04",
                    "Cast-in-situ reinforced concrete culverts (Box culverts)",
                    "m3",
                    1250,
                    4250.00,
                    {"masterformat": "33 42 13", "sans1200": "LB"},
                ),
                (
                    "H.05",
                    "Precast concrete catchpits, manholes & gratings (Catchpits)",
                    "pcs",
                    220,
                    18500.00,
                    {"masterformat": "33 44 13", "sans1200": "LB"},
                ),
                (
                    "H.06",
                    "Stone pitching & gabion erosion protection (Erosion protection)",
                    "m2",
                    4800,
                    685.00,
                    {"masterformat": "31 37 00", "sans1200": "DB"},
                ),
                (
                    "H.07",
                    "Subsoil drainage, perforated pipe & filter (Subsoil drainage)",
                    "m",
                    6800,
                    285.00,
                    {"masterformat": "33 46 16", "sans1200": "DB"},
                ),
                (
                    "H.08",
                    "Stormwater attenuation & detention pond works (Attenuation pond)",
                    "lsum",
                    1,
                    3850000.00,
                    {"masterformat": "33 49 00", "sans1200": "DB"},
                ),
            ],
        ),
        # ── J - Wastewater Treatment Works Extension (SANS 1200 G) ───────
        (
            "J",
            "J - Wastewater Treatment Works Extension",
            {"masterformat": "46", "sans1200": "SANS 1200 G"},
            [
                (
                    "J.01",
                    "Reinforced concrete bioreactor & clarifier tanks, 35 MPa (Process tanks)",
                    "m3",
                    2400,
                    4250.00,
                    {"masterformat": "03 31 00", "sans1200": "G"},
                ),
                (
                    "J.02",
                    "Reinforcement & formwork to process structures (Process concrete works)",
                    "t",
                    320,
                    25500.00,
                    {"masterformat": "03 21 00", "sans1200": "G"},
                ),
                (
                    "J.03",
                    "Fine-bubble aeration, diffusers & blowers (Aeration system)",
                    "lsum",
                    1,
                    6850000.00,
                    {"masterformat": "46 51 00", "sans1200": "G"},
                ),
                (
                    "J.04",
                    "Mechanical screens, grit & inlet works (Inlet works)",
                    "lsum",
                    1,
                    3850000.00,
                    {"masterformat": "46 21 00", "sans1200": "G"},
                ),
                (
                    "J.05",
                    "Sludge dewatering, belt press & handling (Sludge handling)",
                    "lsum",
                    1,
                    4250000.00,
                    {"masterformat": "46 76 00", "sans1200": "G"},
                ),
                (
                    "J.06",
                    "Process pipework, valves & penstocks, stainless (Process pipework)",
                    "lsum",
                    1,
                    3250000.00,
                    {"masterformat": "40 05 00", "sans1200": "G"},
                ),
                (
                    "J.07",
                    "Process electrical, instrumentation & SCADA (Process electrical & SCADA)",
                    "lsum",
                    1,
                    5850000.00,
                    {"masterformat": "40 90 00", "sans1200": "G"},
                ),
                (
                    "J.08",
                    "Final-effluent disinfection, UV & chlorination (Effluent disinfection)",
                    "lsum",
                    1,
                    2450000.00,
                    {"masterformat": "46 66 00", "sans1200": "G"},
                ),
            ],
        ),
        # ── K - Site Reinstatement & Rehabilitation (SANS 1200 M) ────────
        (
            "K",
            "K - Site Reinstatement & Rehabilitation",
            {"masterformat": "32", "sans1200": "SANS 1200 M"},
            [
                (
                    "K.01",
                    "Replace stockpiled topsoil & ameliorate (Topsoil replacement)",
                    "m3",
                    16500,
                    95.00,
                    {"masterformat": "32 91 19", "sans1200": "M"},
                ),
                (
                    "K.02",
                    "Grass & hydroseed disturbed areas & verges (Grassing)",
                    "m2",
                    64000,
                    38.00,
                    {"masterformat": "32 92 19", "sans1200": "M"},
                ),
                (
                    "K.03",
                    "Indigenous, water-wise landscaping & trees (Landscaping)",
                    "lsum",
                    1,
                    1850000.00,
                    {"masterformat": "32 90 00", "sans1200": "M"},
                ),
                (
                    "K.04",
                    "Reinstate fences, gates & boundary works (Fence reinstatement)",
                    "m",
                    3800,
                    685.00,
                    {"masterformat": "32 31 00", "sans1200": "M"},
                ),
                (
                    "K.05",
                    "Clean-up, snag-list & site demobilisation (Site clean-up)",
                    "lsum",
                    1,
                    1450000.00,
                    {"masterformat": "01 74 00", "sans1200": "M"},
                ),
            ],
        ),
    ],
    markups=[
        ("Preliminary & General (P&Gs)", 12.5, "overhead", "direct_cost"),
        ("Contractor's Overheads & Profit", 8.5, "profit", "direct_cost"),
        ("Construction Contingency", 8.0, "contingency", "direct_cost"),
        ("Contract Price Adjustment (CPAP escalation)", 5.0, "overhead", "direct_cost"),
        ("Value-Added Tax (VAT, SARS standard rate)", 15.0, "tax", "cumulative"),
    ],
    total_months=28,
    tender_name="Main Civil Engineering Works (GCC 2015)",
    tender_companies=[
        ("Vosterlan Brink Civils", "tenders@vosterlan.example", 0.99),
        ("Draxen Construction", "estimating@draxen.example", 1.03),
        ("Rondell Construction (Western Cape)", "tenders@rondell.example", 1.00),
    ],
    tender_packages=[
        (
            "Main Civil Engineering Works (GCC 2015)",
            "Earthworks, reservoir, pump station, bulk pipelines, sewers and road pavement.",
            "evaluating",
            [
                ("Vosterlan Brink Civils", "tenders@vosterlan.example", 0.99),
                ("Draxen Construction", "estimating@draxen.example", 1.03),
                ("Rondell Construction (Western Cape)", "tenders@rondell.example", 1.00),
            ],
        ),
        (
            "Mechanical, Electrical & Process Package",
            "Pumps, process plant, MCC, VSDs, SCADA and the wastewater works extension.",
            "issued",
            [
                ("Purolan Projects", "tenders@purolan.example", 1.01),
                ("Filtravon Systems", "bids@filtravon.example", 1.05),
                ("Aquatherne Water Technologies SA", "estimating@aquatherne.example", 1.04),
            ],
        ),
    ],
    project_metadata={
        "address": "Jakes Gerwel Drive, Bishop Lavis, Cape Town 7490, South Africa",
        "client": "City of Cape Town - Water & Sanitation Directorate",
        "consulting_engineer": "Kelbrand Consulting (Pty) Ltd",
        "quantity_surveyor": "Steenkardt Quantity Surveyors (ASAQS)",
        "resident_engineer": "Torbeck Engineering & Architecture",
        "reservoir_capacity_ml": 25,
        "pipeline_length_km": 12,
        "road_length_km": 6,
        "construction_standards": [
            "SANS 1200 Standardized Specification for Civil Engineering Construction",
            "SANS 10100 The structural use of concrete",
            "SANS 1294 Precast concrete manhole sections",
            "TRH 4 Structural design of flexible pavements",
            "TMH road materials & testing manuals",
            "SANS 10400 The application of the National Building Regulations",
        ],
        "measurement_standard": "SANS 1200 (civil engineering measurement & specification)",
        "regulator": "City of Cape Town Metropolitan Municipality; Department of Water and Sanitation (DWS) authorisations",
        "cidb_grade": "8CE (Civil Engineering) - required contractor grading designation",
        "vat_note": "All BOQ rates are exclusive of VAT. South African VAT of 15% (SARS) is applied as a separate markup line.",
        "procurement": "General Conditions of Contract for Construction Works (GCC 2015, SAICE), re-measurable",
        "environmental_note": "Works subject to an approved Environmental Management Programme (EMPr) under NEMA; water-use authorisation under the National Water Act.",
    },
)
